
// TODO

// take an array of stitches as generated by one of our pattern functions
// and a case to identify it by name (ie "Granny Square")

// generate a svg pattern of that pattern
// output svg code text to use in a svg file or html


/** generates svg text for the requested pattern
 * 
 * if pattern is not available, it will print to console and return nothing
 * 
 * @param {Array} stitches - an array of stitch items
 * @param {String} patternName - the name of the pattern (ie "Granny Square"), case insensitive
 * @returns {String | undefined}
 */
function makeVectorPattern(stitches, patternName) {
    if (patternName.toLowerCase() == "granny square") {
        let svgText = makeGrannySquareVector(stitches);
    } else {
        console.log(patternName + " is not an available pattern.");
        return;
    }
    return svgText;
}



